### Paso A: GET (Verificar estado inicial Zig-Zag)
GET http://localhost:5148/api/arbol

### Paso B: POST (Insertar 20 para disparar la rotación RID)
POST http://localhost:5148/api/arbol/insertar
Content-Type: application/json

{
  "id": 20,
  "etiqueta": "Nieto Derecho"
}

### Paso C: GET Final (Verificar que se balanceó el árbol)
GET http://localhost:5148/api/arbol