### Prueba del GET (Ver los nodos iniciales)
GET http://localhost:5156/api/nodos

###

### Prueba del POST (Insertar un nuevo nodo)
POST http://localhost:5156/api/nodos
Content-Type: application/json

{
  "id": 15,
  "valor": "Nuevo Nodo Derecho"
}